package com.omniflux.exchange.export;

import com.omniflux.exchange.Containers;
import com.omniflux.exchange.S3TestBase;
import com.omniflux.exchange.job.JobRepository;
import com.omniflux.exchange.meta.PgMetadataProvider;
import com.omniflux.exchange.seed.SeedService;
import com.omniflux.exchange.security.AuthContext;
import com.omniflux.exchange.security.PrincipalKey;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.sql.DriverManager;
import java.time.Duration;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/** Preclaimed exports through execution, publication and download against real dependencies. */
@SpringBootTest(properties = {
        "omniflux.source.default-adapter=r2dbc",
        "omniflux.security.allowed-relations[0]=audit_fixture",
        "omniflux.source.r2dbc.page-size=2",
        "omniflux.seed.batch-size=2"
})
@ActiveProfiles("demo")
class ExportEndToEndTest extends S3TestBase {
    private static final AuthContext AUTH = new AuthContext(
            new PrincipalKey("audit-test", "exporter", "fixture"), List.of("ANALYST"), "v1");
    @Autowired private SeedService seed;
    @Autowired private ExportService exports;
    @Autowired private JobRepository jobs;
    @Autowired private DatabaseClient database;
    @Autowired private com.omniflux.exchange.job.JobWorker worker;

    @DynamicPropertySource
    static void publicStorageEndpoint(DynamicPropertyRegistry registry) {
        registry.add("omniflux.storage.public-endpoint", Containers::s3Endpoint);
    }

    @BeforeAll
    static void createFixture() throws Exception {
        org.flywaydb.core.Flyway.configure().dataSource(Containers.postgresJdbcUrl(),
                Containers.postgresUser(), Containers.postgresPassword()).load().migrate();
        try (var connection = DriverManager.getConnection(Containers.postgresJdbcUrl(),
                Containers.postgresUser(), Containers.postgresPassword());
             var statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE audit_fixture (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        note text, email text, amount numeric(12,2), enabled boolean,
                        day date, moment timestamp, identifier uuid, payload bytea)
                    """);
        }
    }

    @AfterAll
    static void removeFixture() throws Exception {
        try (var connection = DriverManager.getConnection(Containers.postgresJdbcUrl(),
                Containers.postgresUser(), Containers.postgresPassword());
             var statement = connection.createStatement()) {
            statement.execute("DROP TABLE audit_fixture");
        }
    }

    @ParameterizedTest
    @ValueSource(strings = {"CSV", "XLSX"})
    void seededTypedRowsSurvivePagingPublicationAndPresignedDownload(String format) throws Exception {
        assertEquals(6L, seed.seed("audit_fixture", 6).block());
        assertEquals(6L, seed.seed("audit_fixture", 6).block(), "seeding an existing target must not add rows");
        var metadata = new PgMetadataProvider(database).describe("audit_fixture").block();
        assertNotNull(metadata);
        assertEquals(9, metadata.columns().size());
        assertEquals("id", metadata.keyContract().column());
        // Other cached Spring contexts also have queue pollers. Start with an
        // owned claim so those workers cannot consume a fixture they do not allowlist.
        UUID id = UUID.randomUUID();
        UUID claim = UUID.randomUUID();
        database.sql("""
                INSERT INTO transfer_jobs
                    (id, direction, status, requested_by, issuer, tenant, roles, authz_context_version,
                     relation_name, format, csv_mode, attempt_count, claim_token, worker_id, lease_until, created_at)
                VALUES (:id, 'EXPORT', 'IN_PROGRESS', :subject, :issuer, :tenant, ARRAY['ANALYST']::text[],
                    'v1', 'audit_fixture', :format, 'RAW', 1, :claim, 'e2e-worker',
                    now() + interval '1 minute', now())
                """).bind("id", id).bind("claim", claim).bind("subject", AUTH.key().subject())
                .bind("issuer", AUTH.key().issuer()).bind("tenant", AUTH.key().tenant())
                .bind("format", format).fetch().rowsUpdated().block();
        database.sql("""
                INSERT INTO transfer_job_attempts (job_id, attempt_no, claim_token, worker_id, status, started_at)
                VALUES (:id, 1, :claim, 'e2e-worker', 'IN_PROGRESS', now())
                """).bind("id", id).bind("claim", claim).fetch().rowsUpdated().block();
        worker.run(jobs.find(id).block()).block(Duration.ofSeconds(15));
        var view = exports.detail(id, AUTH).block();
        assertEquals("COMPLETED", view.status(), view.errorMessage());
        assertEquals(6, view.rowCount());
        assertTrue(view.objectKey().contains("/c"));
        assertNotNull(jobs.find(view.id()).block().timingJson());
        assertNotNull(exports.timing(view.id(), AUTH).block());
        assertEquals("COMPLETED", exports.attempts(view.id(), AUTH).block().getFirst().status());
        assertTrue(exports.list(AUTH, 20, null).block().items().stream()
                .anyMatch(item -> item.id().equals(id)));
        var download = exports.download(view.id(), AUTH, "127.0.0.1").block();
        assertNotNull(download);
        try (var client = HttpClient.newHttpClient()) {
            var response = client.send(HttpRequest.newBuilder(download.url()).GET().build(),
                    HttpResponse.BodyHandlers.ofByteArray());
            assertEquals(200, response.statusCode());
            assertEquals(view.byteCount(), response.body().length);
            assertEquals(view.contentSha256(), java.util.HexFormat.of().formatHex(
                    java.security.MessageDigest.getInstance("SHA-256").digest(response.body())));
            if (format.equals("CSV")) {
                String csv = new String(response.body(), java.nio.charset.StandardCharsets.UTF_8);
                assertTrue(csv.contains("quote"));
                assertTrue(csv.contains("seed3@example.test"));
            } else {
                try (var workbook = new org.apache.poi.xssf.usermodel.XSSFWorkbook(
                        new java.io.ByteArrayInputStream(response.body()))) {
                    assertEquals(7, workbook.getSheetAt(0).getPhysicalNumberOfRows());
                }
            }
        }
        assertFalse(jobs.isExpiredAttemptObject(view.objectKey()).block());
    }
}
